"""Build dataset splits for Tuberculosis6208 (AFB / bacilli).

Modes:
  single  -- standard 80/10/10 train/val/test, deterministic.
  5fold   -- 5-fold cross-validation. Each image is in val of exactly one fold.

Output layout:
  single  -> <out>/{train,val,test}/{images,labels}/   + <out>/data.yaml
  5fold   -> <out>/fold_<i>/{train,val}/{images,labels}/ + <out>/fold_<i>/data.yaml
             (no test split inside folds; aggregate across folds)

Pascal-VOC XML (Makerere format: <label>TBbacillus</label>) -> YOLO txt
(class 0 = bacilli, normalized cx cy w h).
"""

from __future__ import annotations

import argparse
import shutil
import sys
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path

import numpy as np
from PIL import Image


# Default label set targets Tuberculosis6208 (Makerere) Pascal-VOC.
# Override via CLI --label-name (repeatable) for other ZN-stain corpora
# that may use different label strings (e.g., "bacilli", "AFB", "MTB").
CLASS_MAP = {"TBbacillus": 0}
CLASS_NAMES = ["bacilli"]


def parse_voc_to_yolo(xml_path: Path, img_w: int, img_h: int) -> list[str]:
    tree = ET.parse(xml_path)
    root = tree.getroot()
    lines: list[str] = []
    for obj in root.iter("object"):
        label_el = obj.find("label")
        if label_el is None:
            label_el = obj.find("name")
        if label_el is None or label_el.text is None:
            continue
        label = label_el.text.strip()
        if label not in CLASS_MAP:
            continue
        cls = CLASS_MAP[label]
        bb = obj.find("bndbox")
        if bb is None:
            continue
        xmin = float(bb.findtext("xmin", "0"))
        ymin = float(bb.findtext("ymin", "0"))
        xmax = float(bb.findtext("xmax", "0"))
        ymax = float(bb.findtext("ymax", "0"))
        xmin = max(0.0, min(img_w, xmin))
        xmax = max(0.0, min(img_w, xmax))
        ymin = max(0.0, min(img_h, ymin))
        ymax = max(0.0, min(img_h, ymax))
        if xmax <= xmin or ymax <= ymin:
            continue
        cx = (xmin + xmax) / 2.0 / img_w
        cy = (ymin + ymax) / 2.0 / img_h
        w = (xmax - xmin) / img_w
        h = (ymax - ymin) / img_h
        lines.append(f"{cls} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
    return lines


def get_image_size(img_path: Path) -> tuple[int, int]:
    with Image.open(img_path) as im:
        return im.size


def maybe_extract_zip(zip_path: Path, extract_dir: Path) -> None:
    if not zip_path.exists():
        return
    if extract_dir.exists() and any(extract_dir.iterdir()):
        return
    extract_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(extract_dir)
    print(f"Extracted {zip_path} -> {extract_dir}")


def collect_pairs(src_dir: Path) -> list[tuple[Path, Path]]:
    pairs: list[tuple[Path, Path]] = []
    for jpg in sorted(src_dir.glob("*.jpg")):
        xml = jpg.with_suffix(".xml")
        if xml.exists():
            pairs.append((jpg, xml))
    return pairs


def write_split(pairs: list[tuple[Path, Path]], out_split: Path) -> tuple[int, int, int]:
    """Returns (n_pairs, n_total_boxes, n_empty_labels)."""
    img_out = out_split / "images"
    lbl_out = out_split / "labels"
    img_out.mkdir(parents=True, exist_ok=True)
    lbl_out.mkdir(parents=True, exist_ok=True)
    n_total_boxes = 0
    n_empty = 0
    for jpg, xml in pairs:
        dst_img = img_out / jpg.name
        if not dst_img.exists():
            shutil.copy2(jpg, dst_img)
        try:
            W, H = get_image_size(jpg)
        except Exception as e:
            print(f"[warn] cannot open {jpg.name}: {e}", file=sys.stderr)
            continue
        lines = parse_voc_to_yolo(xml, W, H)
        lbl_path = lbl_out / (jpg.stem + ".txt")
        lbl_path.write_text("\n".join(lines), encoding="utf-8")
        n_total_boxes += len(lines)
        if not lines:
            n_empty += 1
    return len(pairs), n_total_boxes, n_empty


def write_data_yaml(out_dir: Path, has_test: bool, label: str = "") -> Path:
    yaml_text = (
        f"# Auto-generated by build_split.py  {label}\n"
        f"path: {out_dir.as_posix()}\n"
        f"train: train/images\n"
        f"val:   val/images\n"
    )
    if has_test:
        yaml_text += "test:  test/images\n"
    yaml_text += f"nc: {len(CLASS_NAMES)}\nnames:\n"
    for i, n in enumerate(CLASS_NAMES):
        yaml_text += f"  {i}: {n}\n"
    yaml_path = out_dir / "data.yaml"
    yaml_path.write_text(yaml_text, encoding="utf-8")
    return yaml_path


# ----------------------------------------------------------------------------
# Mode: single (80/10/10)
# ----------------------------------------------------------------------------

def build_single(pairs: list[tuple[Path, Path]], out: Path,
                 train_ratio: float, val_ratio: float, test_ratio: float,
                 seed: int) -> list[str]:
    total_r = train_ratio + val_ratio + test_ratio
    if abs(total_r - 1.0) > 1e-6:
        sys.exit(f"Ratios must sum to 1.0 (got {total_r})")

    rng = np.random.RandomState(seed)
    perm = rng.permutation(len(pairs))
    pairs_shuffled = [pairs[i] for i in perm]

    n_total = len(pairs_shuffled)
    n_train = int(round(n_total * train_ratio))
    n_val = int(round(n_total * val_ratio))
    n_test = n_total - n_train - n_val

    train_pairs = pairs_shuffled[:n_train]
    val_pairs = pairs_shuffled[n_train:n_train + n_val]
    test_pairs = pairs_shuffled[n_train + n_val:]

    print(f"\nSingle split: train={len(train_pairs)} val={len(val_pairs)} "
          f"test={len(test_pairs)} (seed={seed})")

    out.mkdir(parents=True, exist_ok=True)
    stats = {}
    for name, ps in (("train", train_pairs), ("val", val_pairs), ("test", test_pairs)):
        n_p, n_box, n_emp = write_split(ps, out / name)
        stats[name] = (n_p, n_box, n_emp)

    print("\nLabels written:")
    for name, (n_p, n_box, n_emp) in stats.items():
        avg = n_box / max(n_p, 1)
        print(f"  {name:5s}: pairs={n_p:5d}  boxes={n_box:6d}  "
              f"avg/img={avg:5.1f}  empty={n_emp}")
    if any(stats[s][2] > 0.5 * stats[s][0] for s in stats):
        print("\n[WARN] >50% labels empty -- check CLASS_MAP")
    if any(stats[s][1] == 0 for s in stats):
        sys.exit("[FATAL] one split has 0 boxes -- aborting")

    yaml_path = write_data_yaml(out, has_test=True, label="single 80/10/10")
    print(f"\nWrote {yaml_path}")
    return [str(yaml_path)]


# ----------------------------------------------------------------------------
# Mode: 5fold cross-validation
# ----------------------------------------------------------------------------

def build_kfold(pairs: list[tuple[Path, Path]], out: Path,
                n_folds: int, seed: int) -> list[str]:
    rng = np.random.RandomState(seed)
    perm = rng.permutation(len(pairs))
    pairs_shuffled = [pairs[i] for i in perm]

    out.mkdir(parents=True, exist_ok=True)
    n_total = len(pairs_shuffled)
    fold_indices = np.array_split(np.arange(n_total), n_folds)

    print(f"\n{n_folds}-fold split: total={n_total} (seed={seed})")
    yaml_paths = []
    for fold_i in range(n_folds):
        val_idx = set(fold_indices[fold_i].tolist())
        train_pairs = [pairs_shuffled[i] for i in range(n_total) if i not in val_idx]
        val_pairs = [pairs_shuffled[i] for i in range(n_total) if i in val_idx]

        fold_dir = out / f"fold_{fold_i}"
        fold_dir.mkdir(parents=True, exist_ok=True)

        stats = {}
        for name, ps in (("train", train_pairs), ("val", val_pairs)):
            n_p, n_box, n_emp = write_split(ps, fold_dir / name)
            stats[name] = (n_p, n_box, n_emp)

        print(f"\n  Fold {fold_i}: train={stats['train'][0]} val={stats['val'][0]}  "
              f"boxes train={stats['train'][1]} val={stats['val'][1]}")
        if any(stats[s][1] == 0 for s in stats):
            sys.exit(f"[FATAL] fold {fold_i} has 0 boxes in some split -- aborting")

        yaml_path = write_data_yaml(fold_dir, has_test=False,
                                    label=f"fold {fold_i}/{n_folds}")
        yaml_paths.append(str(yaml_path))

    print(f"\nWrote {len(yaml_paths)} fold data.yaml files in {out}")
    return yaml_paths


# ----------------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--zip", default=None, help="optional zip to extract")
    ap.add_argument("--extract-dir", default=None)
    ap.add_argument("--src", required=True, help="dir with jpg+xml pairs")
    ap.add_argument("--out", required=True, help="output base dir")
    ap.add_argument("--mode", default="single", choices=["single", "5fold"])
    ap.add_argument("--seed", type=int, default=42)
    # Single mode ratios
    ap.add_argument("--train-ratio", type=float, default=0.80)
    ap.add_argument("--val-ratio", type=float, default=0.10)
    ap.add_argument("--test-ratio", type=float, default=0.10)
    # k-fold
    ap.add_argument("--n-folds", type=int, default=5)
    ap.add_argument("--label-name", action="append", default=None,
                    help="VOC <label>/<name> string(s) to map to class 0 (bacilli). "
                         "Repeatable. Default: TBbacillus.")
    args = ap.parse_args()

    if args.label_name:
        # Replace default CLASS_MAP with user-supplied labels — all map to class 0
        global CLASS_MAP
        CLASS_MAP = {name: 0 for name in args.label_name}
        print(f"  [class-map] {CLASS_MAP}")

    if args.zip:
        maybe_extract_zip(Path(args.zip), Path(args.extract_dir or "dataset_raw"))

    src = Path(args.src)
    if not src.is_dir():
        sys.exit(f"src dir not found: {src}")
    pairs = collect_pairs(src)
    target_min = 100
    print(f"Image+XML pairs: {len(pairs)}")
    if len(pairs) < target_min:
        sys.exit(f"Too few pairs ({len(pairs)} < {target_min})")

    out = Path(args.out)
    if args.mode == "single":
        build_single(pairs, out, args.train_ratio, args.val_ratio,
                     args.test_ratio, args.seed)
    elif args.mode == "5fold":
        build_kfold(pairs, out, args.n_folds, args.seed)


if __name__ == "__main__":
    main()
